name: Deploy Staging
on:
  push:
    branches:
      - test
    tags:        
      - v*
jobs:
  job-1:
    if: ${{ github.ref_name == test && github.ref_type == 'tag' }} # conditions
    runs-on: ubuntu-latest
    steps:
      - name: "task 1"
        run: echo $GITHUB_REF .'----'. $GITHUB_REF_NAME .'----'. $GITHUB_REF_TYPE