name: Deploy Staging
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: "task 1"
        run: echo $GITHUB_REF .'---'. $GITHUB_REF_NAME .'----'. $GITHUB_REF_TYPE